service: my-llrt-service

provider:
  name: aws
  region: us-west-1
  runtime: provided.al2
  architecture: arm64

plugins:
  - ./plugins/verify-bootstrap

package:
  individually: true
  patterns:
    - "!llrt-upstream/**"
    - "!checker/**"
    - "!archive/**"
    - "!node_modules/**"
    - "!.serverless/**"
    - "!yarn.lock"
    - "!package-lock.json"

functions:
  hello:
    handler: src/hello.handler
    description: "Hello world  in node 22"
    runtime: nodejs22.x
    architecture: arm64
    package:
      patterns:
        - src/hello.js
        - bootstrap
    events:
      - httpApi:
          path: /hello
          method: get

  helloLLRT:
    handler: src/hello.handler
    description: "Hello world in LLRT"
    runtime: provided.al2
    architecture: arm64
    package:
      patterns:
        - src/hello.js
        - bootstrap
    events:
      - httpApi:
          path: /hello-llrt
          method: get

  goodbye:
    handler: src/goodbye.handler
    description: "Goodbye world in node 22"
    runtime: nodejs22.x
    architecture: arm64
    package:
      patterns:
        - src/goodbye.js
    events:
      - httpApi:
          path: /goodbye
          method: get

  goodbyeLLRT:
    handler: src/goodbye.handler
    runtime: provided.al2
    architecture: arm64
    package:
      patterns:
        - src/goodbye.js
        - bootstrap
    events:
      - httpApi:
          path: /goodbye-llrt
          method: get

  test:
    handler: src/test-function.handler
    runtime: nodejs22.x
    architecture: arm64
    package:
      patterns:
        - src/test-function.js
    events:
      - httpApi:
          path: /test
          method: get

  testLLRT:
    handler: src/test-function.handler
    runtime: provided.al2
    architecture: arm64
    package:
      patterns:
        - src/test-function.js
        - bootstrap
    events:
      - httpApi:
          path: /test-llrt
          method: get